from io import BytesIO
from typing import Optional

from weasyprint import HTML


def generate_report_pdf(
    report_name: str,
    period: str,
    sections: list[dict],
    org_name: str = "DoubleHQ",
    client_name: str = "",
) -> bytes:
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            @page {{ size: letter; margin: 2cm; }}
            body {{ font-family: 'Helvetica', sans-serif; color: #1a1a2e; }}
            h1 {{ font-size: 28px; color: #4361ee; margin-bottom: 5px; }}
            h2 {{ font-size: 20px; color: #1a1a2e; margin-top: 30px; border-bottom: 2px solid #4361ee; padding-bottom: 5px; }}
            .subtitle {{ font-size: 14px; color: #666; margin-bottom: 30px; }}
            .section {{ margin-bottom: 25px; }}
            .metric {{ display: inline-block; width: 30%; margin: 1%; padding: 15px; background: #f8f9fa; border-radius: 8px; text-align: center; }}
            .metric-value {{ font-size: 24px; font-weight: bold; color: #4361ee; }}
            .metric-label {{ font-size: 12px; color: #666; }}
            table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
            th {{ background: #4361ee; color: white; padding: 10px; text-align: left; }}
            td {{ padding: 8px 10px; border-bottom: 1px solid #eee; }}
            .footer {{ margin-top: 50px; text-align: center; font-size: 10px; color: #999; }}
        </style>
    </head>
    <body>
        <h1>{report_name}</h1>
        <p class="subtitle">{org_name} — {client_name} — {period}</p>
    """

    for section in sorted(sections, key=lambda s: s.get("sort_order", 0)):
        html_content += f'<div class="section"><h2>{section.get("section_type", "Section").replace("_", " ").title()}</h2>'
        if section.get("data"):
            data = section["data"]
            if isinstance(data, dict):
                html_content += '<div>'
                for k, v in data.items():
                    html_content += f'<div class="metric"><div class="metric-value">{v}</div><div class="metric-label">{k}</div></div>'
                html_content += '</div>'
            elif isinstance(data, list):
                html_content += '<table><tr>'
                for key in data[0].keys():
                    html_content += f'<th>{key}</th>'
                html_content += '</tr>'
                for row in data:
                    html_content += '<tr>'
                    for val in row.values():
                        html_content += f'<td>{val}</td>'
                    html_content += '</tr>'
                html_content += '</table>'
            else:
                html_content += f'<p>{data}</p>'
        html_content += '</div>'

    html_content += f'<div class="footer">Generated by {org_name} | Confidential</div></body></html>'

    pdf_buffer = BytesIO()
    HTML(string=html_content).write_pdf(pdf_buffer)
    return pdf_buffer.getvalue()
